# -*- coding: utf-8 -*-
"""glugtask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mhN_SEv-v2AZeAwYK4O09nWPe9VnCvXs
"""

import pandas as pd
df = pd.read_csv('housing.csv')

df.head(5)

df.describe

import matplotlib.pyplot as plt

list(df.columns.values)

df.values

df_final = df.reset_index()

import matplotlib.pyplot as plt

x = df['RM']
y = df['MEDV']

plt.plot(x, y)

plt.xlabel('x - axis')
plt.ylabel('y - axis')

plt.title('Line graph!')

plt.show()

df.drop(['RM'], axis=1)

df.rename(columns={"LSTAT": "a", "PTRATIO": "c"})

