# -*- coding: utf-8 -*-
"""Task 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hVtEo3qha00LaIPqYGiHNU5Vi3iJvbIN
"""

import json 
import csv 
import time
import datetime
import pandas as pd

with open('/content/Per day prices.json') as json_file: 
    data = json.load(json_file) 
  

date = data

per_day_prices = open('per_day_prices.csv', 'w') 

csv_writer = csv.writer(per_day_prices) 

count = 0
  
for Date in date: 
    if count == 0: 
  
        # Writing headers of CSV file 
        header = Date.keys() 
        csv_writer.writerow(header) 
        count += 1
  
    # Writing data of CSV file 
    csv_writer.writerow(Date.values()) 
  
per_day_prices.close()

data = pd.read_csv("/content/per_day_prices.csv", skipinitialspace=True)
data.date.dtype

data.date = pd.to_datetime(data['date'])
data.head(10)

cols = [data["date"], data["open"]]

headers = ["Date", "Open_Price"]

df = pd.concat(cols, axis=1, keys=headers)
print(df)