# -*- coding: utf-8 -*-
"""Task 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WWXSAlnuMGpCIh7R3TjdwmONY4oiXmnU
"""

import pandas as pd
df = pd.read_csv("/housing.csv")
df.values

unrelated_col = range(len(df),0,-1)
df['Unrelated Column'] = unrelated_col
df

df.drop(["Unrelated Column"], axis=1, inplace=True)
df

df.rename(columns={'LSTAT':'STAT'}, inplace=True)
df

df.iloc[:3]
df.iloc[:100,:]