# -*- coding: utf-8 -*-
"""Task 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1APBfFuxeEjCh_m61S-hKNncwEpuKM0cH
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

df = pd.read_csv("/content/housing.csv")
df.head(5)

plt.figure(figsize=(10,6))

sns.lineplot(x=df['RM'], y=df["MEDV"])

